//
// HistoryAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class HistoryAPI {

    /**
     Delete History Item
     
     - parameter historyItemId: (path) History item ID to be used, you can use GET https://api.elevenlabs.io/v1/history to receive a list of history items and their IDs. 
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteHistoryItemV1HistoryHistoryItemIdDelete(historyItemId: String, xiApiKey: String? = nil, apiResponseQueue: DispatchQueue = ElevenLabsAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteHistoryItemV1HistoryHistoryItemIdDeleteWithRequestBuilder(historyItemId: historyItemId, xiApiKey: xiApiKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete History Item
     - DELETE /v1/history/{history_item_id}
     - Delete a history item by its ID
     - parameter historyItemId: (path) History item ID to be used, you can use GET https://api.elevenlabs.io/v1/history to receive a list of history items and their IDs. 
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func deleteHistoryItemV1HistoryHistoryItemIdDeleteWithRequestBuilder(historyItemId: String, xiApiKey: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/history/{history_item_id}"
        let historyItemIdPreEscape = "\(APIHelper.mapValueToPathItem(historyItemId))"
        let historyItemIdPostEscape = historyItemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{history_item_id}", with: historyItemIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ElevenLabsAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "xi-api-key": xiApiKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ElevenLabsAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Delete History Items
     
     - parameter bodyDeleteHistoryItemsV1HistoryDeletePost: (body)  
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func deleteHistoryItemsV1HistoryDeletePost(bodyDeleteHistoryItemsV1HistoryDeletePost: BodyDeleteHistoryItemsV1HistoryDeletePost, xiApiKey: String? = nil, apiResponseQueue: DispatchQueue = ElevenLabsAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteHistoryItemsV1HistoryDeletePostWithRequestBuilder(bodyDeleteHistoryItemsV1HistoryDeletePost: bodyDeleteHistoryItemsV1HistoryDeletePost, xiApiKey: xiApiKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete History Items
     - POST /v1/history/delete
     - Delete a number of history items by their IDs.
     - parameter bodyDeleteHistoryItemsV1HistoryDeletePost: (body)  
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func deleteHistoryItemsV1HistoryDeletePostWithRequestBuilder(bodyDeleteHistoryItemsV1HistoryDeletePost: BodyDeleteHistoryItemsV1HistoryDeletePost, xiApiKey: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/history/delete"
        let localVariableURLString = ElevenLabsAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyDeleteHistoryItemsV1HistoryDeletePost)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "xi-api-key": xiApiKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ElevenLabsAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Download History Items
     
     - parameter bodyDownloadHistoryItemsV1HistoryDownloadPost: (body)  
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func downloadHistoryItemsV1HistoryDownloadPost(bodyDownloadHistoryItemsV1HistoryDownloadPost: BodyDownloadHistoryItemsV1HistoryDownloadPost, xiApiKey: String? = nil, apiResponseQueue: DispatchQueue = ElevenLabsAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return downloadHistoryItemsV1HistoryDownloadPostWithRequestBuilder(bodyDownloadHistoryItemsV1HistoryDownloadPost: bodyDownloadHistoryItemsV1HistoryDownloadPost, xiApiKey: xiApiKey).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Download History Items
     - POST /v1/history/download
     - Download one or more history items. If one history item ID is provided, we will return a single audio file. If more than one history item IDs are provided, we will provide the history items packed into a .zip file.
     - parameter bodyDownloadHistoryItemsV1HistoryDownloadPost: (body)  
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func downloadHistoryItemsV1HistoryDownloadPostWithRequestBuilder(bodyDownloadHistoryItemsV1HistoryDownloadPost: BodyDownloadHistoryItemsV1HistoryDownloadPost, xiApiKey: String? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/v1/history/download"
        let localVariableURLString = ElevenLabsAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyDownloadHistoryItemsV1HistoryDownloadPost)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "xi-api-key": xiApiKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = ElevenLabsAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get Audio From History Item
     
     - parameter historyItemId: (path) History item ID to be used, you can use GET https://api.elevenlabs.io/v1/history to receive a list of history items and their IDs. 
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAudioFromHistoryItemV1HistoryHistoryItemIdAudioGet(historyItemId: String, xiApiKey: String? = nil, apiResponseQueue: DispatchQueue = ElevenLabsAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return getAudioFromHistoryItemV1HistoryHistoryItemIdAudioGetWithRequestBuilder(historyItemId: historyItemId, xiApiKey: xiApiKey).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Audio From History Item
     - GET /v1/history/{history_item_id}/audio
     - Returns the audio of an history item.
     - parameter historyItemId: (path) History item ID to be used, you can use GET https://api.elevenlabs.io/v1/history to receive a list of history items and their IDs. 
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func getAudioFromHistoryItemV1HistoryHistoryItemIdAudioGetWithRequestBuilder(historyItemId: String, xiApiKey: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/history/{history_item_id}/audio"
        let historyItemIdPreEscape = "\(APIHelper.mapValueToPathItem(historyItemId))"
        let historyItemIdPostEscape = historyItemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{history_item_id}", with: historyItemIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ElevenLabsAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "xi-api-key": xiApiKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = ElevenLabsAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get Generated Items
     
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getGeneratedItemsV1HistoryGet(xiApiKey: String? = nil, apiResponseQueue: DispatchQueue = ElevenLabsAPIAPI.apiResponseQueue, completion: @escaping ((_ data: GetHistoryResponseModel?, _ error: Error?) -> Void)) -> RequestTask {
        return getGeneratedItemsV1HistoryGetWithRequestBuilder(xiApiKey: xiApiKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Generated Items
     - GET /v1/history
     - Returns metadata about all your generated audio.
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - returns: RequestBuilder<GetHistoryResponseModel> 
     */
    open class func getGeneratedItemsV1HistoryGetWithRequestBuilder(xiApiKey: String? = nil) -> RequestBuilder<GetHistoryResponseModel> {
        let localVariablePath = "/v1/history"
        let localVariableURLString = ElevenLabsAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "xi-api-key": xiApiKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetHistoryResponseModel>.Type = ElevenLabsAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
