//
// SamplesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SamplesAPI {

    /**
     Delete Sample
     
     - parameter voiceId: (path) Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices. 
     - parameter sampleId: (path) Sample ID to be used, you can use GET https://api.elevenlabs.io/v1/voices/{voice_id} to list all the available samples for a voice. 
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteSampleV1VoicesVoiceIdSamplesSampleIdDelete(voiceId: String, sampleId: String, xiApiKey: String? = nil, apiResponseQueue: DispatchQueue = ElevenLabsAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteSampleV1VoicesVoiceIdSamplesSampleIdDeleteWithRequestBuilder(voiceId: voiceId, sampleId: sampleId, xiApiKey: xiApiKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Sample
     - DELETE /v1/voices/{voice_id}/samples/{sample_id}
     - Removes a sample by its ID.
     - parameter voiceId: (path) Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices. 
     - parameter sampleId: (path) Sample ID to be used, you can use GET https://api.elevenlabs.io/v1/voices/{voice_id} to list all the available samples for a voice. 
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func deleteSampleV1VoicesVoiceIdSamplesSampleIdDeleteWithRequestBuilder(voiceId: String, sampleId: String, xiApiKey: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/voices/{voice_id}/samples/{sample_id}"
        let voiceIdPreEscape = "\(APIHelper.mapValueToPathItem(voiceId))"
        let voiceIdPostEscape = voiceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voice_id}", with: voiceIdPostEscape, options: .literal, range: nil)
        let sampleIdPreEscape = "\(APIHelper.mapValueToPathItem(sampleId))"
        let sampleIdPostEscape = sampleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{sample_id}", with: sampleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ElevenLabsAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "xi-api-key": xiApiKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ElevenLabsAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get Audio From Sample
     
     - parameter voiceId: (path) Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices. 
     - parameter sampleId: (path) Sample ID to be used, you can use GET https://api.elevenlabs.io/v1/voices/{voice_id} to list all the available samples for a voice. 
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAudioFromSampleV1VoicesVoiceIdSamplesSampleIdAudioGet(voiceId: String, sampleId: String, xiApiKey: String? = nil, apiResponseQueue: DispatchQueue = ElevenLabsAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return getAudioFromSampleV1VoicesVoiceIdSamplesSampleIdAudioGetWithRequestBuilder(voiceId: voiceId, sampleId: sampleId, xiApiKey: xiApiKey).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Audio From Sample
     - GET /v1/voices/{voice_id}/samples/{sample_id}/audio
     - Returns the audio corresponding to a sample attached to a voice.
     - parameter voiceId: (path) Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices. 
     - parameter sampleId: (path) Sample ID to be used, you can use GET https://api.elevenlabs.io/v1/voices/{voice_id} to list all the available samples for a voice. 
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func getAudioFromSampleV1VoicesVoiceIdSamplesSampleIdAudioGetWithRequestBuilder(voiceId: String, sampleId: String, xiApiKey: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/voices/{voice_id}/samples/{sample_id}/audio"
        let voiceIdPreEscape = "\(APIHelper.mapValueToPathItem(voiceId))"
        let voiceIdPostEscape = voiceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{voice_id}", with: voiceIdPostEscape, options: .literal, range: nil)
        let sampleIdPreEscape = "\(APIHelper.mapValueToPathItem(sampleId))"
        let sampleIdPostEscape = sampleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{sample_id}", with: sampleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ElevenLabsAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "xi-api-key": xiApiKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = ElevenLabsAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
