//
// UserAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UserAPI {

    /**
     Get User Info
     
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getUserInfoV1UserGet(xiApiKey: String? = nil, apiResponseQueue: DispatchQueue = ElevenLabsAPIAPI.apiResponseQueue, completion: @escaping ((_ data: UserResponseModel?, _ error: Error?) -> Void)) -> RequestTask {
        return getUserInfoV1UserGetWithRequestBuilder(xiApiKey: xiApiKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get User Info
     - GET /v1/user
     - Gets information about the user
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - returns: RequestBuilder<UserResponseModel> 
     */
    open class func getUserInfoV1UserGetWithRequestBuilder(xiApiKey: String? = nil) -> RequestBuilder<UserResponseModel> {
        let localVariablePath = "/v1/user"
        let localVariableURLString = ElevenLabsAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "xi-api-key": xiApiKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserResponseModel>.Type = ElevenLabsAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get User Subscription Info
     
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getUserSubscriptionInfoV1UserSubscriptionGet(xiApiKey: String? = nil, apiResponseQueue: DispatchQueue = ElevenLabsAPIAPI.apiResponseQueue, completion: @escaping ((_ data: ExtendedSubscriptionResponseModel?, _ error: Error?) -> Void)) -> RequestTask {
        return getUserSubscriptionInfoV1UserSubscriptionGetWithRequestBuilder(xiApiKey: xiApiKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get User Subscription Info
     - GET /v1/user/subscription
     - Gets extended information about the users subscription
     - parameter xiApiKey: (header) Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the &#39;Profile&#39; tab on the website. (optional)
     - returns: RequestBuilder<ExtendedSubscriptionResponseModel> 
     */
    open class func getUserSubscriptionInfoV1UserSubscriptionGetWithRequestBuilder(xiApiKey: String? = nil) -> RequestBuilder<ExtendedSubscriptionResponseModel> {
        let localVariablePath = "/v1/user/subscription"
        let localVariableURLString = ElevenLabsAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "xi-api-key": xiApiKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ExtendedSubscriptionResponseModel>.Type = ElevenLabsAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
