//
// AddVoiceResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddVoiceResponseModel: Codable, JSONEncodable, Hashable {

    public var voiceId: String

    public init(voiceId: String) {
        self.voiceId = voiceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case voiceId = "voice_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(voiceId, forKey: .voiceId)
    }
}

