//
// GetHistoryResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetHistoryResponseModel: Codable, JSONEncodable, Hashable {

    public var history: [HistoryItemResponseModel]

    public init(history: [HistoryItemResponseModel]) {
        self.history = history
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case history
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(history, forKey: .history)
    }
}

