//
// GetVoicesResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetVoicesResponseModel: Codable, JSONEncodable, Hashable {

    public var voices: [VoiceResponseModel]

    public init(voices: [VoiceResponseModel]) {
        self.voices = voices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case voices
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(voices, forKey: .voices)
    }
}

