//
// InvoiceResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InvoiceResponseModel: Codable, JSONEncodable, Hashable {

    public var amountDueCents: Int
    public var nextPaymentAttemptUnix: Int

    public init(amountDueCents: Int, nextPaymentAttemptUnix: Int) {
        self.amountDueCents = amountDueCents
        self.nextPaymentAttemptUnix = nextPaymentAttemptUnix
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amountDueCents = "amount_due_cents"
        case nextPaymentAttemptUnix = "next_payment_attempt_unix"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amountDueCents, forKey: .amountDueCents)
        try container.encode(nextPaymentAttemptUnix, forKey: .nextPaymentAttemptUnix)
    }
}

