//
// Settings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The settings for a specific voice. */
public struct Settings: Codable, JSONEncodable, Hashable {

    public var stability: Double
    public var similarityBoost: Double

    public init(stability: Double, similarityBoost: Double) {
        self.stability = stability
        self.similarityBoost = similarityBoost
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case stability
        case similarityBoost = "similarity_boost"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(stability, forKey: .stability)
        try container.encode(similarityBoost, forKey: .similarityBoost)
    }
}

