//
// UserResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserResponseModel: Codable, JSONEncodable, Hashable {

    public var subscription: SubscriptionResponseModel
    public var isNewUser: Bool
    public var xiApiKey: String

    public init(subscription: SubscriptionResponseModel, isNewUser: Bool, xiApiKey: String) {
        self.subscription = subscription
        self.isNewUser = isNewUser
        self.xiApiKey = xiApiKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subscription
        case isNewUser = "is_new_user"
        case xiApiKey = "xi_api_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subscription, forKey: .subscription)
        try container.encode(isNewUser, forKey: .isNewUser)
        try container.encode(xiApiKey, forKey: .xiApiKey)
    }
}

